# bands

Query data cube properties



```{r include=FALSE}
library(gdalcubes)
```

## Description

Query data cube properties


## Usage


```r
bands(obj)

```


## Arguments

| Argument    | Description                       |
|:------------|:----------------------------------|
| obj | a data cube proxy object (class cube) |


## Value

A data.frame with rows representing the bands and columns representing properties of a band (name, type, scale, offset, unit)


## Examples


```{r}
# create image collection from example Landsat data only 
# if not already done in other examples
if (!file.exists(file.path(tempdir(), "L8.db"))) {
  L8_files <- list.files(system.file("L8NY18", package = "gdalcubes"),
                         ".TIF", recursive = TRUE, full.names = TRUE)
  create_image_collection(L8_files, "L8_L1TP", file.path(tempdir(), "L8.db"), quiet = TRUE) 
}

L8.col = image_collection(file.path(tempdir(), "L8.db"))
v = cube_view(extent=list(left=388941.2, right=766552.4, 
              bottom=4345299, top=4744931, t0="2018-04", t1="2018-06"),
              srs="EPSG:32618", nx = 497, ny=526, dt="P1M")
bands(raster_cube(L8.col, v))
```


