# extent

Derive the spatiotemporal extent of an image collection



```{r include=FALSE}
library(gdalcubes)
```

## Description

Derive the spatiotemporal extent of an image collection


## Usage


```r
extent(x, srs = "EPSG:4326")

```


## Arguments

| Argument    | Description                       |
|:------------|:----------------------------------|
| x | image collection proxy object |
| srs | target spatial reference system |


## Value

a list with elements `left`, `right`, `bottom`, `top`, `t0` (start date/time), and `t1` (end date/time)


## Examples


```{r}
# create image collection from example Landsat data only 
# if not already done in other examples
if (!file.exists(file.path(tempdir(), "L8.db"))) {
  L8_files <- list.files(system.file("L8NY18", package = "gdalcubes"),
                         ".TIF", recursive = TRUE, full.names = TRUE)
  create_image_collection(L8_files, "L8_L1TP", file.path(tempdir(), "L8.db"), quiet = TRUE) 
}

L8.col = image_collection(file.path(tempdir(), "L8.db"))
extent(L8.col,"EPSG:32618")
cube_view(extent=extent(L8.col,"EPSG:32618"),
          srs="EPSG:32618", nx = 497, ny=526, dt="P1M")
```


