
# Get started

## Step 1: Install the gdalcubes R package  from CRAN


```{r, eval=FALSE}
install.packages("gdalcubes")
```


## Step 2: Download example data (740 MB)


```{r, include = FALSE}
need_download = !dir.exists("L8_Amazon")
```

```{r download, eval = need_download}
download.file("https://uni-muenster.sciebo.de/s/e5yUZmYGX0bo4u9/download", destfile = "L8_Amazon.zip")
unzip("L8_Amazon.zip", exdir = "L8_Amazon")
```

## Step 3: Create an image collection


```{r}
library(gdalcubes)
files = list.files("L8_Amazon", recursive = TRUE, 
                   full.names = TRUE, pattern = ".tif") 
L8.col = create_image_collection(files, format = "L8_SR")
L8.col
```


## Step 4: Create a data cube


```{r}
v= cube_view(extent=L8.col, dt="P1Y", dx=1000, dy=1000, 
             srs="EPSG:3857", aggregation = "median")
x = raster_cube(L8.col, v) 
x
```

## Step 5: Process the data cube and plot

```{r}
gdalcubes_options(parallel = 4)
x |>
  select_bands(c("B02","B03","B04")) |>
  reduce_time(c("median(B02)","median(B03)","median(B04)")) |>
  plot(x, rgb=3:1, zlim=c(0,1200))
```



